### ISSUE TITLE
Something doesn't make sense in listener, maybe a bug

### ISSUE THREAD

**Issue by kodyfanz** [Bisonai/orakl#474] opened 2023-04-03 14:19 UTC
In the code bellow, `observedBlock` is always `latestBlock` in any case, so `contract.queryFilter(listener.eventName, observedBlock, latestBlock)` will filter from `latestBlock` to `latestBlock`, this doesn't make sense
https://github.com/Bisonai/orakl/blob/bbe32cd19e3d840acb8a0a5b40c65e7db2840f81/core/src/listener/listener.ts#L38-L52
If the intent is to query events from the last observed block up to the latest block, the code should create `const fromBlock = observedBlock` before update `observedBlock = latestBlock` and edit query to `contract.queryFilter(listener.eventName, fromBlock, latestBlock)`

**Comment by martinkersner** [comment] 2023-04-04 05:37
Hello @kodyfanz,

We are aware of this issues and currently investigating this as well. Due to the above described bug, some blocks can be missed.

Cheers,
Martin

**Comment by martinkersner** [comment] 2023-04-05 05:55
This issue is duplicate of https://github.com/Bisonai/orakl/issues/465. Closing this issue. All further communication will be done through the #465

**Closed by martinkersner** 2023-04-05 05:55 UTC
Labels: bug
